### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by hzoo** [sdkennedy/babel-preset-target#1]
Not sure if you saw but we've wanted to do something like this for a while! https://github.com/babel/notes/blob/master/2016-07/july-31.md#babel-preset-env-autoprefixer-for-babel-pr-3476

https://github.com/babel/babel/pull/3476, https://github.com/babel/babel-preset-env (just started)

So we'd love to be able to work together, and move into the babel org once it's ready if that's cool.

I actually found this when searching for a name - I was thinking babel-preset-env and was looking at babel-preset-target on npm and saw it was already published!
- I think we could also include the different modules (amd,umd,systemjs), and stage-x plugins as well so users wouldn't need to specify any of those seperately (like in https://github.com/babel/babel-preset-env)

cc @baer

**Comment by baer** [comment]
A quick peek through this code and I'm really impressed. I love the caniuse DB and you've done a good job with some of the mappings already. I'd love to help out if there is need.

**Comment by sdkennedy** [comment]
Hey thanks! Sorry for the delayed response, I was pretty busy at work. I'd definitely be down to collaborate.

What I'm currently working on right now is if a given transform can be skipped we should still include any syntax plugins that are necessary for babel to parse that functionality.

**Comment by hzoo** [comment]
K closing since we've started working on https://github.com/babel/babel-preset-env - will be trying to incorporate the ideas in this preset too

**Comment by sdkennedy** [comment]
Sounds good

**Comment by hzoo** [comment]
@sdkennedy just wanted to reach out again! Just made https://github.com/babel/babel-preset-env 1.0 and wanted to ask if you wanted to be a collab? I know you've done some awesome stuff here and I'd appreciate the help if you have the time!

**Comment by sdkennedy** [comment]
Hey @hzoo. Thanks for reaching out. It looks like babel-preset-env has come a long way! I'd love to help out where I can. I think I'll actually add a comment on this repo marking it deprecated in favor of your repo.

**Comment by hzoo** [comment]
Cool! I'l add you and you can make an issue about the things that env might be missing that target did? Let me know (and free feel to join our https://slack.babeljs.io)

**Comment by sdkennedy** [comment]
Sounds great :)
